#!/bin/sh

# To comment out lines in ed or vim
# ┌──────────┐
# │Use :.!cmt│
# └──────────┘
# ┌──────────────┐
# │Use :.,.+2!cmt│
# └──────────────┘

# By default it adds "# " (Hash + space)
# for alternatives, pass the desired character
# special characters must be escaped
# ┌─────────────┐
# │Use :.!cmt \"│
# └─────────────┘

# Added spaces must be single quoted.
# ┌────────────────┐
# │Use :.!cmt '   '│
# └────────────────┘

while read -r line; do
    echo "${1:-#} $line"
done
