#! /bin/bash
#
# USE: pdfnotes example.pdf
#
# Help turning a PDF of lecture slides into
# a markdown file, ready to use for note-taking.
# Aimed at bullet-point presentations
#
# It is just a series of steps I use to prep a
# PowerPoint ready for note-taking in lectures.
# The PowerPoint must be exported as a pdf, first
#
# If you are looking to convert a PDF to a
# markdown file, this is not what you want.

FILENAME=${1}
BASENAME=$( echo ${1} | cut -d '.' -f 1 )
EXTENSION=$( echo ${1} | cut -d '.' -f 2 )
OUTNAME=${BASENAME}.markdown

echo "file name: ${FILENAME}"
echo "base name: ${BASENAME}"
echo "extension: ${EXTENSION}"

# Check for just one argument
if [[ ${#} != 1 ]]; then
    echo
    echo "Enter pdf filename"
    echo "EXAMPLE: pdfnotes test.pdf"
    echo
    exit
fi;

# Check file extension
if [[ ${EXTENSION} != "pdf" ]]; then
    echo
    echo "File must be a pdf"
    echo "EXAMPLE: filename.pdf"
    echo
    exit
fi;

pdftotext ${1} ${OUTNAME}

# Replace strage bullet points at start of line
sed -i "s/^[^a-zA-Z0-9]/  + /" ${OUTNAME}

# Add indent to lines starting with lower case
sed -i '/^[a-z]/ s/^/    /' ${OUTNAME}
# sed -i '/STATD_PORT/ s/^/#/' /tmp/file
